#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx
# Create a simple HTML file with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
# Start nginx service
sudo service nginx start
