#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index

# Multiline replacement for the Nginx configuration file
new_string="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/www/html;
    index index;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

# Use sed to replace the content inside the server block
sudo sed -i '/server {/,$d' /etc/nginx/sites-available/default
echo "${new_string}" | sudo tee -a /etc/nginx/sites-available/default

sudo service nginx restart
