#!/usr/bin/env bash
# Configure Nginx to install, redirect, and set up a custom 404 page

# Update package lists and install nginx
apt-get -y update
apt-get -y install nginx

# Allow Nginx HTTP through UFW
sudo ufw allow 'Nginx HTTP'

# Create the default index page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create the custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Modify the Nginx configuration to add redirection and custom 404 error page
sudo sed -i '/server {/a\\tlocation = /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/server {/a\\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
