#!/bin/bash

# Variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE

# Confirm the creation
if [ $? -eq 0 ]; then
  echo "RSA key pair created successfully."
else
  echo "Failed to create RSA key pair."
fi
